
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int tkBooleana = 13;
  public static final int tkNumero = 18;
  public static final int tkConcatenacion = 9;
  public static final int tkFlecha = 4;
  public static final int tkMinuscula = 16;
  public static final int tkChar = 21;
  public static final int tkEspeciales = 19;
  public static final int tkDosPuntos = 3;
  public static final int tkPuntoComa = 15;
  public static final int tkLlaveC = 8;
  public static final int tkLlaveA = 7;
  public static final int tkRconj = 2;
  public static final int EOF = 0;
  public static final int tkPositiva = 12;
  public static final int tkMayuscula = 17;
  public static final int tkPorcentaje = 14;
  public static final int tkComa = 5;
  public static final int error = 1;
  public static final int tkIdentificador = 20;
  public static final int tkOnda = 6;
  public static final int tkDisyuncion = 10;
  public static final int tkKleene = 11;
  public static final int tkString = 22;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "tkRconj",
  "tkDosPuntos",
  "tkFlecha",
  "tkComa",
  "tkOnda",
  "tkLlaveA",
  "tkLlaveC",
  "tkConcatenacion",
  "tkDisyuncion",
  "tkKleene",
  "tkPositiva",
  "tkBooleana",
  "tkPorcentaje",
  "tkPuntoComa",
  "tkMinuscula",
  "tkMayuscula",
  "tkNumero",
  "tkEspeciales",
  "tkIdentificador",
  "tkChar",
  "tkString"
  };
}

